### ISSUE TITLE
Some Languages are missing from Languages.md

### ISSUE THREAD

**Issue by LassazVegaz** [fharookshaik/fibonacci-series#150]
Some languages such as PHP, JavaScript, R, etc. have Fibonacci implementations but they are missing from the [Languages.md](https://github.com/fharookshaik/fibonacci-series/blob/9caab1e79388d37328f73494a0f24dd3336f59a0/Languages.md) file.

**Comment by MrJithil** [comment]
Please add `hacktoberfest`

**Comment by LassazVegaz** [comment]
> Please add `hacktoberfest`

What is `hacktoberfest`?

**Comment by MrJithil** [comment]
> > Please add `hacktoberfest`
> 
> What is `hacktoberfest`?

Its a different story. Please ignore.
