### ISSUE TITLE
[no-heading-punctuation] Don’t add a trailing `?` to headings

### ISSUE THREAD

**Issue by fharookshaik** [fharookshaik/fibonacci-series#23]
#### Occurred on:
+ **Commit**:  17ab232211e99a0748c983ed07b991f92063f45a
+ **File**:    [README.md](https://github.com/fharookshaik/fibonacci_series/blob/17ab232211e99a0748c983ed07b991f92063f45a/README.md)
+ **LineNum**: [7](https://github.com/fharookshaik/fibonacci_series/blob/17ab232211e99a0748c983ed07b991f92063f45a/README.md#L7)
+ **Code**:    `## What is fibonacci series though?`

    
#### Currently on:
+ **Commit**:  abf622dc08c1b5515193b57802747919267c9ca9
+ **File**:    [README.md](https://github.com/fharookshaik/fibonacci_series/blob/abf622dc08c1b5515193b57802747919267c9ca9/README.md)
+ **LineNum**: [7](https://github.com/fharookshaik/fibonacci_series/blob/abf622dc08c1b5515193b57802747919267c9ca9/README.md#L7)

**Comment by ulieckstein** [comment]
added PR with fix
